git:
  depth: 1
language: node_js
node_js:
  - 8.8.0
matrix:
  fast_finish: true
notifications:
  email:
    - delhibabu86@gmail.com
branches:
  only:
    - master
deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  # Make sure you have skip_cleanup set to true, otherwise Travis CI will delete all the files created during the build, which will probably delete what you are trying to upload.
  skip_cleanup: true
  keep-history: true
  on:
    branch: master
env:
  global:
        secure:erQjBxta5fL8f2kx4JSlcFo+RbUySivuuf5ksjI/HYt1fL8qEQnyH2ZilfihbNlmUW2AhgMN6/BXgYAC/ndKLfZgVLALtNfCvyMHig6xczNYjvFJjIG/nfQD1s7VlOm6Rb0flZSYuLtbRlDpSK9qrJbuLdoe+xqTw0ieGLGRwLVS9ANiOfujjenZNkeBTqjlPQs/gQVY+1GmzukjO5KxNz2fvi11JzZWkA/hgS1l3ffojmcEfVMMMvweqnDHUr3XQHv42uV94ZFFlBownHQt+hzZfNUPq6wjCDx51WnkBfqeIBuaawOHnfjFjzRYbk1hW8eUqBQOx0qHvml0iC99Iv7GHONJVro5j3+kHuw+T9dMrQ4RUg7cGRzauSdcCFjMZdxDuhwk/I0A9fLHPcG0AeOpojqMdRpHcnDIj3rGynbULaQyoNgf0UHoFjRyj4Q2YNoZBvx5hd/gpCVx/lypZoMYzmKl/76RixWvWaekqtn9oSpKQNdZdlHjNwWHiLYR5GbFwpoGXIrvDJKQnd5eigaW6jewMkKPYoCAorbhwDKb21HSw/qjVB1IY/lF8JA1xK89nSbq4cNJOMOgF6oBnXAYpviOWAqKKwxpI+0xmZOoaie+s6oO+sjnxI2wV6ZQGZAf2CPBl7USSSFN9dl+IJw2CI8QcmFUdID9dqvKhI0=